@startuml
'https://plantuml.com/class-diagram

package dynamodb {

    package dataqualitycheck {
        class DataQualityScanner {
            - dataQualityPercentage : double
            - model : String
            - threshold : double
            - invalidAttributes : List<String>
            - static final INVALID_ATTRIBUTE_REPLACER : String

            + DataQualityScanner(model : String, threshold : double) : void
            + scan() : void
            + printQualityPercentage() : void
            + getQualityPercentage() : double
        }
    }

    package espnDAO {

        class espnDAO {
            - static THRESHOLD : double
            - static INVALID_STRING_REPLACER : String

            + requestQuery() throws IOException : JSONObject
            + extractSchedule(espnResponse : JSONObject) : String
            + extractEvents(espnResponse : JSONObject) : List<String>
            + extractTeam(team : JSONObject, leagueId : String) : String
            + extractLeague(league : JSONObject) : String
        }

        package constants {

            class espnRequestConstants {
                + static final NBA : String
                + static final NHL : String
                + static final yyyyMMdd : DateTimeFormatter
                + static final mm_dd_yy : DateTimeFormatter
                + static final NOW : LocalDateTime
                + static final START_DATE : String
                + static final RANGE_DAYS : long
                + static final END_DATE : String
            }
        }
    }

    package oddsDAO {

        class oddsDAO {

        }

        package constants {

            class oddsRequestConstants {

            }
        }
    }

    package models {
        class Event {
            - eventId : String
            - eventName : String
            - eventNameShort : String
            - eventHeadline : String
            - leagueId : String
            - eventDate : String
            - eventSeasonId : String
            - teamHome : String
            - teamAway : String
            - eventStatusId : String
            - eventStatus : String
            - teamWinner : String
            - scoreHome : Integer
            - scoreAway : Integer
            - scoreTotal : Integer
            - links : List<String>

            + getField() : Object
            + setField(value : String) : void
        }

        class Schedule {
            - scheduleId : String
            - leagueId : String
            - leagueName : String
            - timestamp : String
            - eventIdList : List<String>
            - dateRange : String
            - scheduleName : String

            + getField() : Object
            + setField(value : String) : void
        }

        class Bet {
            - betId : String
            - userId : String
            - eventId : String
            - amountWagered : BigDecimal
            - odds : BigDecimal
            - teamBetOn : String
            - projection : BigDecimal
            - bettingMarket : String
            - bookmakerId : String
            - datePlaced : String
            - gainOrLoss : BigDecimal
            - teamHome : String
            - scoreHome : Integer
            - teamHomeLogo : String
            - teamAway : String
            - scoreAway : Integer
            - teamAwayLogo : String
            - teamWinner : String
            - scoreTotal : Integer
            - eventName : String
            - eventHeadline : String
            - eventDate : String
            - eventStatus : String

            + getField() : Object
            + setField(value : String) : void
        }

        package assets {

            class League {
                - leagueId : String
                - leagueName : String
                - seasonStatusId : String
                - seasonStatus : String
                - seasonYear : String
                - leagueLogo : String

                + getField() : Object
                + setField(value : String) : void
            }

            class Team {
                - leagueId : String
                - teamId : String
                - teamName : String
                - teamNameAbr : String
                - teamLogo : String
                - teamColor : String
                - teamAlternateColor : String
                - teamLinks : List<String>

                + getField() : Object
                + setField(value : String) : void
            }
        }

        package bettinghistory {

            class WeeklyHistory {
                - weeklyHistoryId : String
                - userId : String
                - weeklyHistoryName : String
                - date : String
                - weeklyBetCount : Integer
                - weeklyAmountWagered : BigDecimal
                - weeklyGain : BigDecimal
                - weeklyLoss : BigDecimal
                - weeklyBetIdList : List<String>
                - weeklySummary : Map<String, BigDecimal>

                + getField() : Object
                + setField(value : String) : void
            }

            class YearlyHistory {
                - yearlyHistoryId : String
                - userId : String
                - yearlyHistoryName : String
                - date : String
                - weeklyHistoryIds : List<String>
                - yearlyBetCount : Integer
                - yearlyAmountWagered : BigDecimal
                - yearlyGain : BigDecimal
                - yearlyLoss : BigDecimal
                - yearlyBetIdList : List<String>
                - yearlySummary : Map<String, BigDecimal>

                + getField() : Object
                + setField(value : String) : void
            }
        }
    }
}


package exceptions {

    package dataqualityexception {

        class DataQualityException {
            - dataQualityPercentage : double
            - model : String
            - threshold : double
            - invalidAttributes : List<String>

            + scan() : void
            + getQualityPercentage() : double
        }

        package modelexceptions {
            exception EventDataQualityException {}
            exception LeagueDataQualityException {}
            exception ScheduleDataQualityException {}
            exception TeamDataQualityException {}
        }
    }
}


package models {

    class ScheduleModel {
        - scheduleId : String
        - leagueId : String
        - leagueName : String
        - timestamp : String
        - eventIdList : List<String>
        - dateRange : String
        - scheduleName : String

        + getField() : Object
        + builder() : Builder
    }

    class EventModel {
        - eventId : String
        - eventName : String
        - eventNameShort : String
        - eventHeadline : String
        - leagueId : String
        - eventDate : String
        - eventSeasonId : String
        - teamHome : String
        - teamAway : String
        - eventStatusId : String
        - eventStatus : String
        - teamWinner : String
        - scoreHome : Integer
        - scoreAway : Integer
        - scoreTotal : Integer
        - links : List<String>

        + getField() : Object
        + builder() : Builder
    }

    class BetModel {
        - betId : String
        - userId : String
        - eventId : String
        - amountWagered : BigDecimal
        - odds : BigDecimal
        - teamBetOn : String
        - projection : BigDecimal
        - bettingMarket : String
        - bookmakerId : String
        - datePlaced : String
        - gainOrLoss : BigDecimal
        - teamHome : String
        - scoreHome : Integer
        - teamHomeLogo : String
        - teamAway : String
        - scoreAway : Integer
        - teamAwayLogo : String
        - teamWinner : String
        - scoreTotal : Integer
        - eventName : String
        - eventHeadline : String
        - eventDate : String
        - eventStatus : String

        + getField() : Object
        + builder() : Builder
    }

    package assets {

        class LeagueModel {
            - leagueId : String
            - leagueName : String
            - seasonStatusId : String
            - seasonStatus : String
            - seasonYear : String
            - leagueLogo : String

            + getField() : Object
            + builder() : Builder
        }

        class TeamModel {
            - leagueId : String
            - teamId : String
            - teamName : String
            - teamNameAbr : String
            - teamLogo : String
            - teamColor : String
            - teamAlternateColor : String
            - teamLinks : List<String>

            + getField() : Object
            + builder() : Builder
        }

        class BookmakerModel {

        }
    }

    package bettinghistory {

        class WeeklyHistoryModel {
            - weeklyHistoryId : String
            - userId : String
            - weeklyHistoryName : String
            - date : String
            - weeklyBetCount : Integer
            - weeklyAmountWagered : BigDecimal
            - weeklyGain : BigDecimal
            - weeklyLoss : BigDecimal
            - weeklyBetIdList : List<String>
            - weeklySummary : Map<String, BigDecimal>

            + getField() : Object
            + builder() : Builder
        }

        class YearlyHistoryModel {
            - yearlyHistoryId : String
            - userId : String
            - yearlyHistoryName : String
            - date : String
            - weeklyHistoryIds : List<String>
            - yearlyBetCount : Integer
            - yearlyAmountWagered : BigDecimal
            - yearlyGain : BigDecimal
            - yearlyLoss : BigDecimal
            - yearlyBetIdList : List<String>
            - yearlySummary : Map<String, BigDecimal>

            + getField() : Object
            + builder() : Builder
        }
    }
}

dynamodb.espnDAO.espnDAO --> dynamodb.espnDAO.constants.espnRequestConstants

dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.Schedule
dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.Event
dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.Bet
dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.assets.Team
dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.assets.League
dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.bettinghistory.WeeklyHistory
dynamodb.espnDAO.espnDAO -[#blue,thickness=2]> dynamodb.models.bettinghistory.YearlyHistory

dynamodb.espnDAO.espnDAO --> dynamodb.dataqualitycheck.DataQualityScanner

dynamodb.oddsDAO.oddsDAO --> dynamodb.oddsDAO.constants.oddsRequestConstants

dynamodb.oddsDAO.oddsDAO -[#red,thickness=2]> dynamodb.models.assets.Bookmaker

dynamodb.oddsDAO.oddsDAO --> dynamodb.dataqualitycheck.DataQualityScanner

dynamodb.dataqualitycheck.DataQualityScanner --> exceptions.dataqualityexception.DataQualityException

exceptions.dataqualityexception.DataQualityException --> exceptions.dataqualityexception.modelexceptions.ScheduleDataQualityException
exceptions.dataqualityexception.DataQualityException --> exceptions.dataqualityexception.modelexceptions.EventDataQualityException
exceptions.dataqualityexception.DataQualityException --> exceptions.dataqualityexception.modelexceptions.LeagueDataQualityException
exceptions.dataqualityexception.DataQualityException --> exceptions.dataqualityexception.modelexceptions.TeamDataQualityException

models.ScheduleModel --- dynamodb.models.Schedule
models.EventModel --- dynamodb.models.Event
models.BetModel --- dynamodb.models.Bet
models.assets.LeagueModel --- dynamodb.models.assets.League
models.assets.TeamModel --- dynamodb.models.assets.Team
models.assets.BookmakerModel --- dynamodb.models.assets.Bookmaker
models.bettinghistory.WeeklyHistoryModel --- dynamodb.models.bettinghistory.WeeklyHistory
models.bettinghistory.YearlyHistoryModel --- dynamodb.models.bettinghistory.YearlyHistory

@enduml