/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookiepedia;

import bookiepedia.dependencies.ServiceComponent;
import bookiepedia.dynamodb.EspnDAO.EspnDAO;
import org.json.JSONObject;

public class App {

    private static EspnDAO espn = new EspnDAO();

    /**
     * Main method.
     * @param args - Arguments
     */
    public static void main(String[] args) {

    }
}
