/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookiepedia;

import bookiepedia.dynamodb.espnDAO.espnDAO;
import org.json.JSONObject;

public class App {

    private static espnDAO espn = new espnDAO();

    public static void main(String[] args) {
        try {
            JSONObject espnJson = espn.requestQuery();

            System.out.println(espnJson);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
