/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookiepedia;

import bookiepedia.dynamodb.ESPNdao;
import org.json.JSONObject;

import java.util.stream.Stream;

public class App {

    private static ESPNdao espn = new ESPNdao();

    public static void main(String[] args) {
        try {
            JSONObject espnJson = espn.requestQuery();

            System.out.println(espnJson);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
