name: Project Pipeline

on:
  push:
    branches:
      - 'main'
      - 'feature**'

env:

  API_BASE_URL: ${{ secrets.API_BASE_URL }}
  COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
  COGNITO_REDIRECT_SIGNIN: ${{ secrets.COGNITO_REDIRECT_SIGNIN }}
  COGNITO_REDIRECT_SIGNOUT: ${{ secrets.COGNITO_REDIRECT_SIGNOUT }}

  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
  COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.COGNITO_USER_POOL_CLIENT_ID }}

  GH_PACKAGE_REG_READ_USER: ${{ secrets.GH_PACKAGE_REG_READ_USER }}
  GH_PACKAGE_REG_READ_PASS: ${{ secrets.GH_PACKAGE_REG_READ_PASS }}
  
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml

  STACK_NAME: bookiepedia
  PIPELINE_EXECUTION_ROLE: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
  CLOUDFORMATION_EXECUTION_ROLE: ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}
  ARTIFACTS_BUCKET: ${{ secrets.ARTIFACTS_BUCKET }}
  REGION: us-east-2
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:

  build-feature:
    # this stage is triggered only for feature branches (feature*),
    # which will build the stack and deploy to a stack named with branch name.
    if: startsWith(github.ref, 'refs/heads/feature')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-Java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: aws-actions/setup-sam@v2
      - run: sam build --template ${SAM_TEMPLATE}

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Build SAM resources
        shell: bash
        run: |
          sam build --template ${SAM_TEMPLATE}

  build-and-package-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/setup-node@v4
      - uses: aws-actions/setup-sam@v2

      - name: Build SAM resources
        run: |
          sam build --template ${SAM_TEMPLATE}

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: prod-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload SAM artifacts to artifact buckets
        run: |
          sam package \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --region ${REGION} \
            --output-template-file packaged-prod.yaml

      - uses: actions/upload-artifact@v4
        with:
          name: packaged-prod.yaml
          path: packaged-prod.yaml

      - name: Install NPM dependencies
        working-directory: web
        run: npm install

      - name: Create .env file for npm build
        working-directory: web
        run: |
          touch .env

          echo VITE_API_BASE_URL=\"$API_BASE_URL\" >> .env

          echo VITE_COGNITO_DOMAIN=\"${COGNITO_DOMAIN}.auth.us-east-2.amazoncognito.com\" >> .env

          echo VITE_COGNITO_USER_POOL_ID=\"$COGNITO_USER_POOL_ID\" >> .env
          echo VITE_COGNITO_USER_POOL_CLIENT_ID=\"$COGNITO_USER_POOL_CLIENT_ID\" >> .env

          echo VITE_COGNITO_REDIRECT_SIGNIN=\"$COGNITO_REDIRECT_SIGNIN\" >> .env
          echo VITE_COGNITO_REDIRECT_SIGNOUT=\"$COGNITO_REDIRECT_SIGNOUT\" >> .env

      - name: Build NPM static resources
        working-directory: web
        run: npm run build

      - name: Upload NPM static build output
        uses: actions/upload-artifact@v4
        with:
          name: static-build
          path: web/dist

  deploy-to-aws:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-package-main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-node@v4
      - uses: aws-actions/setup-sam@v2
      - uses: actions/download-artifact@v4
        with:
          name: packaged-prod.yaml

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to testing account
        # Added COGNITO_DOMAIN_PREFIX so that I can copy+paste the full cognito domain address into secrets like the others
        # Referenced in --parameter-overrides 
        run: |
          COGNITO_DOMAIN_PREFIX=$(echo ${COGNITO_DOMAIN} | cut -d'.' -f1)
          sam deploy --stack-name ${STACK_NAME} \
            --template packaged-prod.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${REGION} \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --parameter-overrides "S3Bucket=${ARTIFACTS_BUCKET} CognitoDomain=${COGNITO_DOMAIN_PREFIX} FrontendDeployment=remote" \
            --role-arn ${CLOUDFORMATION_EXECUTION_ROLE}

      - name: Download NPM static resources
        uses: actions/download-artifact@v4
        with:
          name: static-build
          path: dist/static

      - name: Deploy NPM static resources
        run: |
          aws s3 cp \
            dist/static \
            s3://${ARTIFACTS_BUCKET}/static/ \
            --recursive